/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.stefanlezaic.zeleznice.srbije.admin.view.component;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Stefan
 */
public class PanelStanica extends javax.swing.JPanel {

    /**
     * Creates new form PanelStanica
     */
    public PanelStanica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNazivFrejma = new javax.swing.JLabel();
        lblNazivStanice = new javax.swing.JLabel();
        txtNazivStanice = new javax.swing.JTextField();
        cmbMestaZaStanice = new javax.swing.JComboBox();
        btnUnesiStanicu = new javax.swing.JButton();
        lblMesto = new javax.swing.JLabel();

        lblNazivFrejma.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblNazivFrejma.setForeground(new java.awt.Color(255, 255, 255));
        lblNazivFrejma.setText("Unos stanice");

        lblNazivStanice.setForeground(new java.awt.Color(255, 255, 255));
        lblNazivStanice.setText("Naziv stanice:");

        txtNazivStanice.setBackground(new java.awt.Color(102, 102, 102));
        txtNazivStanice.setForeground(new java.awt.Color(0, 0, 0));

        cmbMestaZaStanice.setBackground(new java.awt.Color(153, 153, 153));
        cmbMestaZaStanice.setForeground(new java.awt.Color(0, 0, 0));

        btnUnesiStanicu.setBackground(new java.awt.Color(153, 153, 153));
        btnUnesiStanicu.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnUnesiStanicu.setForeground(new java.awt.Color(0, 0, 0));
        btnUnesiStanicu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/icons8_add_64px_2.png"))); // NOI18N
        btnUnesiStanicu.setText("Unesi stanicu");
        btnUnesiStanicu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiStanicuActionPerformed(evt);
            }
        });

        lblMesto.setForeground(new java.awt.Color(255, 255, 255));
        lblMesto.setText("Mesto:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUnesiStanicu, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNazivFrejma, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblMesto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)
                            .addComponent(cmbMestaZaStanice, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblNazivStanice, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)
                            .addComponent(txtNazivStanice, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNazivFrejma, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNazivStanice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNazivStanice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMesto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMestaZaStanice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(btnUnesiStanicu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnesiStanicuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiStanicuActionPerformed

    }//GEN-LAST:event_btnUnesiStanicuActionPerformed

    public JButton getBtnUnesiStanicu() {
        return btnUnesiStanicu;
    }

    public JComboBox getCmbMestaZaStanice() {
        return cmbMestaZaStanice;
    }

    public JTextField getTxtNazivStanice() {
        return txtNazivStanice;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUnesiStanicu;
    private javax.swing.JComboBox cmbMestaZaStanice;
    private javax.swing.JLabel lblMesto;
    private javax.swing.JLabel lblNazivFrejma;
    private javax.swing.JLabel lblNazivStanice;
    private javax.swing.JTextField txtNazivStanice;
    // End of variables declaration//GEN-END:variables

    public void btnUnesiStanicu(ActionListener actionListener) {
        btnUnesiStanicu.addActionListener(actionListener);
    }
}
