/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.stefanlezaic.zeleznice.srbije.admin.view.component;

import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Stefan
 */
public class PanelStanica extends javax.swing.JPanel {

    /**
     * Creates new form PanelStanica
     */
    public PanelStanica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNazivFrejma = new javax.swing.JLabel();
        lblNazivStanice = new javax.swing.JLabel();
        txtNazivStanice = new javax.swing.JTextField();
        cmbMestaZaStanice = new javax.swing.JComboBox();
        btnUnesiStanicu = new javax.swing.JButton();
        lblMesto = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNazivFrejma.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblNazivFrejma.setForeground(new java.awt.Color(255, 255, 255));
        lblNazivFrejma.setText("Unos stanice");
        add(lblNazivFrejma, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 50));

        lblNazivStanice.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNazivStanice.setForeground(new java.awt.Color(255, 255, 255));
        lblNazivStanice.setText("Naziv stanice:");
        lblNazivStanice.setToolTipText("");
        add(lblNazivStanice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 160, 40));

        txtNazivStanice.setBackground(new java.awt.Color(102, 102, 102));
        txtNazivStanice.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtNazivStanice.setForeground(new java.awt.Color(0, 0, 0));
        add(txtNazivStanice, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 300, 40));

        cmbMestaZaStanice.setBackground(new java.awt.Color(153, 153, 153));
        cmbMestaZaStanice.setForeground(new java.awt.Color(0, 0, 0));
        add(cmbMestaZaStanice, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 300, 40));

        btnUnesiStanicu.setBackground(new java.awt.Color(153, 153, 153));
        btnUnesiStanicu.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnUnesiStanicu.setForeground(new java.awt.Color(0, 0, 0));
        btnUnesiStanicu.setText("Unesi stanicu");
        btnUnesiStanicu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiStanicuActionPerformed(evt);
            }
        });
        add(btnUnesiStanicu, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 300, 60));

        lblMesto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblMesto.setForeground(new java.awt.Color(255, 255, 255));
        lblMesto.setText("Mesto stanice:");
        lblMesto.setToolTipText("");
        add(lblMesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 160, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnesiStanicuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiStanicuActionPerformed

    }//GEN-LAST:event_btnUnesiStanicuActionPerformed

    public JButton getBtnUnesiStanicu() {
        return btnUnesiStanicu;
    }

    public JComboBox getCmbMestaZaStanice() {
        return cmbMestaZaStanice;
    }

    public JTextField getTxtNazivStanice() {
        return txtNazivStanice;
    }

    public JLabel getLblMesto() {
        return lblMesto;
    }

    public JLabel getLblNazivFrejma() {
        return lblNazivFrejma;
    }

    public JLabel getLblNazivStanice() {
        return lblNazivStanice;
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUnesiStanicu;
    private javax.swing.JComboBox cmbMestaZaStanice;
    private javax.swing.JLabel lblMesto;
    private javax.swing.JLabel lblNazivFrejma;
    private javax.swing.JLabel lblNazivStanice;
    private javax.swing.JTextField txtNazivStanice;
    // End of variables declaration//GEN-END:variables

    public void btnUnesiStanicuMouseListener(MouseListener mouseListener) {
        btnUnesiStanicu.addMouseListener(mouseListener);
    }
}
