/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.stefanlezaic.zeleznice.srbije.admin.form;

import java.awt.Dimension;
import javax.swing.JDialog;
import javax.swing.JPanel;
import rs.stefanlezaic.zeleznice.srbije.admin.view.component.PanelSat;
import rs.stefanlezaic.zeleznice.srbije.admin.view.kontroler.KontrolerLinija;
import rs.stefanlezaic.zeleznice.srbije.admin.view.kontroler.KontrolerMedjustanica;
import rs.stefanlezaic.zeleznice.srbije.admin.view.kontroler.KontrolerPolazak;
import rs.stefanlezaic.zeleznice.srbije.admin.view.kontroler.KontrolerStanica;
import rs.stefanlezaic.zeleznice.srbije.admin.view.kontroler.KontrolerUpravljanjePolascima;
import rs.stefanlezaic.zeleznice.srbije.lib.sat.Sat;
import rs.stefanlezaic.zeleznice.srbije.lib.theme.Tema;

/**
 *
 * @author Stefan
 */
public class GlavniFrame extends javax.swing.JFrame {

    private final Tema tema = new Tema(this);
    private Sat sat;

    public GlavniFrame() {
        initComponents();
        this.pack();
        this.setMinimumSize(new Dimension(1500, 800));

        sat = new Sat(getPanelSat1().getLblVreme(), getPanelSat1().getLblDatum());
        sat.pokreniSat();
        KontrolerStanica kontrolerStanica = new KontrolerStanica(panelLinija.getPanelStanica(), this);
        KontrolerLinija kontrolerLinija = new KontrolerLinija(panelLinija.getPanelLinija(), this);
        KontrolerMedjustanica kontrolerMedjustanica = new KontrolerMedjustanica(panelLinija.getPanelMedjustanice(), this);
        KontrolerPolazak kontrolerPolazak = new KontrolerPolazak(panelPolazak.getPanelPolazak(), this);
        KontrolerUpravljanjePolascima kontrolerUpravljanjePolascima = new KontrolerUpravljanjePolascima(panelUpravljanjePolascima.getPanelSviPolasci(), this);

        ukljuciDarkMode();
        jPanelLinija.setVisible(true);
        jPanelPolazak.setVisible(false);
        jPanelUpravljanjePolascima.setVisible(false);
    }
     private void ukljuciDarkMode() {
        lblWhiteMode.setVisible(true);
        lblDarkMode.setVisible(false);
        tema.blackTheme();
    }

    private void iskljuciDarkMode() {
        lblWhiteMode.setVisible(false);
        lblDarkMode.setVisible(true);
        tema.whiteTheme();
    }

    public JPanel getPanelBar() {
        return panelBar;
    }

    public PanelSat getPanelSat1() {
        return panelSat1;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBar = new javax.swing.JPanel();
        panelSat1 = new rs.stefanlezaic.zeleznice.srbije.admin.view.component.PanelSat();
        lblDarkMode = new javax.swing.JLabel();
        lblWhiteMode = new javax.swing.JLabel();
        jPanelUpravljanjePolascima = new javax.swing.JPanel();
        panelUpravljanjePolascima = new rs.stefanlezaic.zeleznice.srbije.admin.view.PanelUpravljanjePolascima();
        jPanelPolazak = new javax.swing.JPanel();
        panelPolazak = new rs.stefanlezaic.zeleznice.srbije.admin.view.PanelPolazak();
        jPanelLinija = new javax.swing.JPanel();
        panelLinija = new rs.stefanlezaic.zeleznice.srbije.admin.view.PanelLinija();
        jSeparator1 = new javax.swing.JSeparator();
        menuBar = new javax.swing.JMenuBar();
        meniLinija = new javax.swing.JMenu();
        meniPolazak = new javax.swing.JMenu();
        meniUpravljanjePolascima = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblDarkMode.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDarkMode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/darkMode.png"))); // NOI18N
        lblDarkMode.setText("Tamno");
        lblDarkMode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDarkModeMouseClicked(evt);
            }
        });

        lblWhiteMode.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblWhiteMode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/whiteMode.png"))); // NOI18N
        lblWhiteMode.setText("Svetlo");
        lblWhiteMode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblWhiteModeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBarLayout = new javax.swing.GroupLayout(panelBar);
        panelBar.setLayout(panelBarLayout);
        panelBarLayout.setHorizontalGroup(
            panelBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarLayout.createSequentialGroup()
                .addGroup(panelBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDarkMode, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWhiteMode, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSat1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBarLayout.setVerticalGroup(
            panelBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarLayout.createSequentialGroup()
                .addGroup(panelBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDarkMode, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWhiteMode, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(336, Short.MAX_VALUE))
        );

        jPanelUpravljanjePolascima.setPreferredSize(new java.awt.Dimension(1300, 600));

        javax.swing.GroupLayout jPanelUpravljanjePolascimaLayout = new javax.swing.GroupLayout(jPanelUpravljanjePolascima);
        jPanelUpravljanjePolascima.setLayout(jPanelUpravljanjePolascimaLayout);
        jPanelUpravljanjePolascimaLayout.setHorizontalGroup(
            jPanelUpravljanjePolascimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUpravljanjePolascimaLayout.createSequentialGroup()
                .addComponent(panelUpravljanjePolascima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanelUpravljanjePolascimaLayout.setVerticalGroup(
            jPanelUpravljanjePolascimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUpravljanjePolascimaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelUpravljanjePolascima, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelPolazakLayout = new javax.swing.GroupLayout(jPanelPolazak);
        jPanelPolazak.setLayout(jPanelPolazakLayout);
        jPanelPolazakLayout.setHorizontalGroup(
            jPanelPolazakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPolazakLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelPolazak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelPolazakLayout.setVerticalGroup(
            jPanelPolazakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPolazakLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelPolazak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanelLinijaLayout = new javax.swing.GroupLayout(jPanelLinija);
        jPanelLinija.setLayout(jPanelLinijaLayout);
        jPanelLinijaLayout.setHorizontalGroup(
            jPanelLinijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLinijaLayout.createSequentialGroup()
                .addComponent(panelLinija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanelLinijaLayout.setVerticalGroup(
            jPanelLinijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLinijaLayout.createSequentialGroup()
                .addComponent(panelLinija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.SE_RESIZE_CURSOR));
        jSeparator1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        meniLinija.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/meni_linija_80px.png"))); // NOI18N
        meniLinija.setText("Linija");
        meniLinija.setFont(new java.awt.Font("Nirmala UI", 3, 24)); // NOI18N
        meniLinija.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meniLinijaMouseClicked(evt);
            }
        });
        menuBar.add(meniLinija);

        meniPolazak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/meni_oblak_voz_100.png"))); // NOI18N
        meniPolazak.setText("Polazak");
        meniPolazak.setFont(new java.awt.Font("Nirmala UI", 3, 24)); // NOI18N
        meniPolazak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meniPolazakMouseClicked(evt);
            }
        });
        menuBar.add(meniPolazak);

        meniUpravljanjePolascima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/meni_lista_svi_polasci_100px.png"))); // NOI18N
        meniUpravljanjePolascima.setText("Upravljanje polascima");
        meniUpravljanjePolascima.setFont(new java.awt.Font("Nirmala UI", 3, 24)); // NOI18N
        meniUpravljanjePolascima.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meniUpravljanjePolascimaMouseClicked(evt);
            }
        });
        menuBar.add(meniUpravljanjePolascima);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1490, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelLinija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanelPolazak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanelUpravljanjePolascima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(panelBar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 4, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelLinija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanelPolazak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanelUpravljanjePolascima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(panelBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(0, 4, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblDarkModeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDarkModeMouseClicked
        ukljuciDarkMode();
    }//GEN-LAST:event_lblDarkModeMouseClicked

    private void lblWhiteModeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblWhiteModeMouseClicked
        iskljuciDarkMode();
    }//GEN-LAST:event_lblWhiteModeMouseClicked

    private void meniLinijaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meniLinijaMouseClicked
        jPanelLinija.setVisible(true);
        jPanelPolazak.setVisible(false);
        jPanelUpravljanjePolascima.setVisible(false);
    }//GEN-LAST:event_meniLinijaMouseClicked

    private void meniPolazakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meniPolazakMouseClicked
        jPanelLinija.setVisible(false);
        jPanelPolazak.setVisible(true);
        jPanelUpravljanjePolascima.setVisible(false);
    }//GEN-LAST:event_meniPolazakMouseClicked

    private void meniUpravljanjePolascimaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meniUpravljanjePolascimaMouseClicked
        jPanelLinija.setVisible(false);
        jPanelPolazak.setVisible(false);
        jPanelUpravljanjePolascima.setVisible(true);
    }//GEN-LAST:event_meniUpravljanjePolascimaMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelLinija;
    private javax.swing.JPanel jPanelPolazak;
    private javax.swing.JPanel jPanelUpravljanjePolascima;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDarkMode;
    private javax.swing.JLabel lblWhiteMode;
    private javax.swing.JMenu meniLinija;
    private javax.swing.JMenu meniPolazak;
    private javax.swing.JMenu meniUpravljanjePolascima;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel panelBar;
    private rs.stefanlezaic.zeleznice.srbije.admin.view.PanelLinija panelLinija;
    private rs.stefanlezaic.zeleznice.srbije.admin.view.PanelPolazak panelPolazak;
    private rs.stefanlezaic.zeleznice.srbije.admin.view.component.PanelSat panelSat1;
    private rs.stefanlezaic.zeleznice.srbije.admin.view.PanelUpravljanjePolascima panelUpravljanjePolascima;
    // End of variables declaration//GEN-END:variables
}
