/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.stefanlezaic.zeleznice.srbije.admin.view;

import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author Stefan
 */
public class PanelUpravljanjePolascima extends javax.swing.JPanel {

    /**
     * Creates new form PanelSviPolasci
     */
    public PanelUpravljanjePolascima() {
        initComponents();
    }

    public JButton getBtnObrisiPolazakIzTabeleSviPolasci() {
        return btnObrisiPolazakIzTabeleSviPolasci;
    }

    public JButton getBtnOsveziListuSviPolasci() {
        return btnOsveziListuSviPolasci;
    }

    public JButton getBtnUpdejtuj() {
        return btnUpdejtuj;
    }

    public JComboBox<String> getCmbSortiraj() {
        return cmbSortiraj;
    }

    public JScrollPane getjScrollPane3() {
        return jScrollPane3;
    }

    public JLabel getLblLista() {
        return lblLista;
    }

    public JLabel getLblSort() {
        return lblSort;
    }

    public JTable getTabelaSviPolasci() {
        return tabelaSviPolasci;
    }

   
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaSviPolasci = new javax.swing.JTable();
        btnOsveziListuSviPolasci = new javax.swing.JButton();
        btnObrisiPolazakIzTabeleSviPolasci = new javax.swing.JButton();
        btnUpdejtuj = new javax.swing.JButton();
        lblLista = new javax.swing.JLabel();
        cmbSortiraj = new javax.swing.JComboBox<>();
        lblSort = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1590, 690));
        setMinimumSize(new java.awt.Dimension(1590, 690));
        setPreferredSize(new java.awt.Dimension(1590, 690));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelaSviPolasci.setBackground(new java.awt.Color(153, 153, 153));
        tabelaSviPolasci.setForeground(new java.awt.Color(0, 0, 0));
        tabelaSviPolasci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaSviPolasci.setFocusable(false);
        tabelaSviPolasci.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabelaSviPolasci.setRowHeight(25);
        tabelaSviPolasci.setShowVerticalLines(false);
        tabelaSviPolasci.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tabelaSviPolasci);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1280, 550));

        btnOsveziListuSviPolasci.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnOsveziListuSviPolasci.setText("Osvezi listu");
        add(btnOsveziListuSviPolasci, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 220, 60));

        btnObrisiPolazakIzTabeleSviPolasci.setBackground(new java.awt.Color(153, 153, 153));
        btnObrisiPolazakIzTabeleSviPolasci.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnObrisiPolazakIzTabeleSviPolasci.setForeground(new java.awt.Color(0, 0, 0));
        btnObrisiPolazakIzTabeleSviPolasci.setText("Obrisi polazak");
        add(btnObrisiPolazakIzTabeleSviPolasci, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 620, 300, 60));

        btnUpdejtuj.setBackground(new java.awt.Color(153, 153, 153));
        btnUpdejtuj.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnUpdejtuj.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdejtuj.setText("Izmeni polazak");
        add(btnUpdejtuj, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 620, 300, 60));

        lblLista.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblLista.setForeground(new java.awt.Color(255, 255, 255));
        lblLista.setText("Tabela svih polazaka");
        add(lblLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 40));

        cmbSortiraj.setBackground(new java.awt.Color(153, 153, 153));
        cmbSortiraj.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cmbSortiraj.setForeground(new java.awt.Color(0, 0, 0));
        cmbSortiraj.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "po datumu u opadajucem", "po datumu u rastucem ", "po liniji " }));
        add(cmbSortiraj, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, 220, 40));

        lblSort.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSort.setForeground(new java.awt.Color(255, 255, 255));
        lblSort.setText("Sortiraj:");
        add(lblSort, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, 110, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObrisiPolazakIzTabeleSviPolasci;
    private javax.swing.JButton btnOsveziListuSviPolasci;
    private javax.swing.JButton btnUpdejtuj;
    private javax.swing.JComboBox<String> cmbSortiraj;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblLista;
    private javax.swing.JLabel lblSort;
    private javax.swing.JTable tabelaSviPolasci;
    // End of variables declaration//GEN-END:variables

    public void btnObrisiPolazakIzTabeleSviPolasciActionListener(ActionListener actionListener) {
        btnObrisiPolazakIzTabeleSviPolasci.addActionListener(actionListener);
    }

    public void btnUpdejtujActionListener(ActionListener actionListener) {
        btnUpdejtuj.addActionListener(actionListener);
    }

    public void btnOsveziListuSviPolasciActionListener(ActionListener actionListener) {
        btnOsveziListuSviPolasci.addActionListener(actionListener);
    }

    public void cmbSortirajItemListener(ItemListener itemListener) {
        cmbSortiraj.addItemListener(itemListener);
    }

    

}
