/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.stefanlezaic.zeleznice.srbije.admin.view;

import rs.stefanlezaic.zeleznice.srbije.admin.view.component.PanelMedjustanice;
import rs.stefanlezaic.zeleznice.srbije.admin.view.component.PanelStanica;

/**
 *
 * @author Stefan
 */
public class PanelLinija extends javax.swing.JPanel {

    /**
     * Creates new form PanelLinija
     */
    public PanelLinija() {
        initComponents();
    }

    public rs.stefanlezaic.zeleznice.srbije.admin.view.component.PanelLinija getPanelLinija() {
        return panelLinija;
    }

    

    public PanelMedjustanice getPanelMedjustanice() {
        return panelMedjustanice;
    }

    

    public PanelStanica getPanelStanica() {
        return panelStanica;
    }

   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLinija = new rs.stefanlezaic.zeleznice.srbije.admin.view.component.PanelLinija();
        panelMedjustanice = new rs.stefanlezaic.zeleznice.srbije.admin.view.component.PanelMedjustanice();
        panelStanica = new rs.stefanlezaic.zeleznice.srbije.admin.view.component.PanelStanica();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(panelLinija, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 480, 310));
        add(panelMedjustanice, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 660, 560));
        add(panelStanica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 480, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rs.stefanlezaic.zeleznice.srbije.admin.view.component.PanelLinija panelLinija;
    private rs.stefanlezaic.zeleznice.srbije.admin.view.component.PanelMedjustanice panelMedjustanice;
    private rs.stefanlezaic.zeleznice.srbije.admin.view.component.PanelStanica panelStanica;
    // End of variables declaration//GEN-END:variables
}
