/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.stefanlezaic.zeleznice.srbije.admin.view;

import rs.stefanlezaic.zeleznice.srbije.admin.view.component.PanelMedjustanice;
import rs.stefanlezaic.zeleznice.srbije.admin.view.component.PanelStanica;

/**
 *
 * @author Stefan
 */
public class PanelLinija extends javax.swing.JPanel {

    /**
     * Creates new form PanelLinija
     */
    public PanelLinija() {
        initComponents();
    }

    public rs.stefanlezaic.zeleznice.srbije.admin.view.component.PanelLinija getPanelLinija1() {
        return panelLinija1;
    }

    public void setPanelLinija1(rs.stefanlezaic.zeleznice.srbije.admin.view.component.PanelLinija panelLinija1) {
        this.panelLinija1 = panelLinija1;
    }

    public PanelMedjustanice getPanelMedjustanice1() {
        return panelMedjustanice1;
    }

    public void setPanelMedjustanice1(PanelMedjustanice panelMedjustanice1) {
        this.panelMedjustanice1 = panelMedjustanice1;
    }

    public PanelStanica getPanelStanica1() {
        return panelStanica1;
    }

    public void setPanelStanica1(PanelStanica panelStanica1) {
        this.panelStanica1 = panelStanica1;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLinija1 = new rs.stefanlezaic.zeleznice.srbije.admin.view.component.PanelLinija();
        panelMedjustanice1 = new rs.stefanlezaic.zeleznice.srbije.admin.view.component.PanelMedjustanice();
        panelStanica1 = new rs.stefanlezaic.zeleznice.srbije.admin.view.component.PanelStanica();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(panelLinija1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        add(panelMedjustanice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 660, 560));
        add(panelStanica1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 460, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rs.stefanlezaic.zeleznice.srbije.admin.view.component.PanelLinija panelLinija1;
    private rs.stefanlezaic.zeleznice.srbije.admin.view.component.PanelMedjustanice panelMedjustanice1;
    private rs.stefanlezaic.zeleznice.srbije.admin.view.component.PanelStanica panelStanica1;
    // End of variables declaration//GEN-END:variables
}
